export const coffee = {
  title1: "커피",
  title1Item1: "스타벅스 원두",
  title1Item2: "스타벅스 비아",
  title1Item3: "스타벅스앳홈 by 캡슐",
  title2: "나와 어울리는 커피",
  title3: "스타벅스 리저브™",
  title3Item1: "RESERVE MAGAZINE",
  title4: "에스프레소 음료",
  title4Item1: "도피오",
  title4Item2: "에스프레소 마키아또",
  title4Item3: "아메리카노",
  title4Item4: "마키아또",
  title4Item5: "카푸치노",
  title4Item6: "라떼",
  title4Item7: "모카",
  title5: "최상의 커피를 즐기는 법",
  title5Item1: "커피 프레스",
  title5Item2: "푸어 오버",
  title5Item3: "아이스 푸어 오버",
  title5Item4: "커피 메이커",
  title5Item5: "리저브를 매장에서 다양하게 즐기는법",
  title6: "커피 이야기",
  title6Item1: "농장에서 우리의 손으로",
  title6Item2: "최상의 아라비카 원두",
  title6Item3: "스타벅스 로스트 스펙트럼",
  title6Item4: "스타벅스 디카페인",
  title6Item5: "클로버® 커피 추출 시스템",
};

export const menu = {
  title1: "음료",
  title2: "푸드",
  title3: "상품",
  title4: "카드",
  title5: "메뉴 이야기",
};